### ISSUE TITLE
Add shadow to ad cards.

### ISSUE THREAD

**Issue by kevcamel** [classifiedz/classifiedz.github.io#91] opened 2017-10-03 04:12 UTC
Add a slight shadow to cards, similar to material design. This enhancement is said to be implemented to mimic paper to make it easier on the eyes and friendlier for the user to read.

**Comment by laurie-y** [comment] 2017-10-07 02:54
This was done wasn't it?

**Comment by laurie-y** [comment] 2017-10-07 03:03
Duplicate of issue #107 
Completed with commit 54b1f05

**Closed as completed by laurie-y** 2017-10-07 03:03 UTC
Labels: duplicate, Invalid
